name: tongarirosp-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets>=0.6.0
  - mkl
  - scikit-learn
  - pandas
  - pip:
    - pymatsolver
    - discretize
    - colorcet
    - git+https://github.com/simpeg/simpeg.git@miller_tongariro_2018
